# .github/workflows/build.yml

name: Build Standalone BCML Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: macOS Fix – Install gettext for Python 3.8
        if: runner.os == 'macOS'
        run: |
          brew install gettext
          brew link gettext --force
          echo "DYLD_LIBRARY_PATH=/usr/local/opt/gettext/lib" >> $GITHUB_ENV

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: x64

      - name: Install Rust (for zstandard, etc.)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          DYLD_LIBRARY_PATH: /usr/local/opt/gettext/lib

      - name: Install PyInstaller
        run: pip install pyinstaller
        env:
          DYLD_LIBRARY_PATH: /usr/local/opt/gettext/lib

      - name: Build Executable
        run: |
          pyinstaller --onefile \
            --name bcml-${{ runner.os }}-${{ github.ref_name }} \
            --icon bcml/data/bcml.ico \
            -c bcml/__main__.py
        env:
          DYLD_LIBRARY_PATH: /usr/local/opt/gettext/lib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bcml-${{ runner.os }}-${{ github.ref_name }}
          path: dist/bcml-${{ runner.os }}-${{ github.ref_name }}
