# .github/workflows/build.yml

name: Build Standalone BCML Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: macOS Fix – Use Homebrew Python 3.8
        if: runner.os == 'macOS'
        run: |
          brew install python@3.8
          echo "/usr/local/opt/python@3.8/bin" >> $GITHUB_PATH
          echo "PYTHON_LOCATION=/usr/local/opt/python@3.8/bin/python3.8" >> $GITHUB_ENV

      - name: Set up Python 3.8 (Linux/Windows only)
        if: runner.os != 'macOS'
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: x64

      - name: Display Python version
        run: python3 --version || python --version

      - name: Install Rust (for zstandard, etc.)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt || pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip3 install pyinstaller || pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile \
            --name bcml-${{ runner.os }}-${{ github.ref_name }} \
            --icon bcml/data/bcml.ico \
            -c bcml/__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bcml-${{ runner.os }}-${{ github.ref_name }}
          path: dist/bcml-${{ runner.os }}-${{ github.ref_name }}
