# .github/workflows/build.yml

name: Build Standalone BCML Executables

on:
  workflow_dispatch:

env:
  BCML_VERSION: 3.10.9

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.8 (latest available)
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: x64

      - name: Install Rust (for zstandard, etc.)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Locate botw_hashed_names.txt from aamp
        id: locate_aamp
        run: |
          echo "AAMP_TXT=$(python get_requirements.py)" >> $GITHUB_ENV
        shell: bash

      - name: Build Executable (Linux)
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile --name bcml --icon bcml/data/bcml.ico -c bcml/__main__.py --add-data "${{ env.AAMP_TXT }}:aamp"

      - name: Build Executable (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --name bcml --icon bcml/data/bcml.ico -c bcml/__main__.py --add-data "${{ env.AAMP_TXT }};aamp"
        shell: pwsh

      - name: Rename Windows binary
        if: runner.os == 'Windows'
        run: Rename-Item -Path dist\bcml.exe -NewName bcml-windows-${{ env.BCML_VERSION }}.exe
        shell: pwsh

      - name: Rename Linux binary
        if: runner.os == 'Linux'
        run: mv dist/bcml dist/bcml-linux-${{ env.BCML_VERSION }}

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: bcml-windows-${{ env.BCML_VERSION }}
          path: dist/bcml-windows-${{ env.BCML_VERSION }}.exe

      - name: Upload artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: bcml-linux-${{ env.BCML_VERSION }}
          path: dist/bcml-linux-${{ env.BCML_VERSION }}
